### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by LifeIsStrange** [kodi-web/web.browser.chromium#1]
Thank you a lot :D besides the servo layout engine will get support for the CEF, so in the near future we will have maybe the servo engine in Kodi ! 
Sorry for my bad english and thanks for all your awesome and open source works, I love you men.

**Comment by AlwinEsch** [comment]
No problem, yes with servo engine is also one goal for me. 

If everything comes fine, then can also a add-on insert a skin xml with reference to the web browser control and a local URL can be loaded with own programmed add-on code in e.g. Javascript (and everything else supported from Chrome) which then available in Kodi.

I'm now a bit more on my project and hope on the next time bigger steps to do.

Sorry for my late answer, development code is still on my own account here https://github.com/AlwinEsch/web.browser.chromium and not not looked here. 

Currently I add also a small help description (Temporary) to the wiki of this repository that why I seen your message.

My English is also not the best ;)

Thanks a lot back

**Comment by LifeIsStrange** [comment]
This is absolutely not a big deal for the late reply! 
I'm existed about the next of the development :)

**Comment by AlwinEsch** [comment]
Today was so much fixed that I has created a small demo video for youtube, see https://youtu.be/iQ20aA0_ZWU :)
